name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # necessário para commitar no branch gh-pages

jobs:
  publish:
    name: Publish to gh-pages
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Cria js/firebaseConfig.js com as chaves dos Secrets
      - name: Generate firebaseConfig.js
        run: |
          mkdir -p js
          cat <<EOF > js/firebaseConfig.js
          /* --------- GERADO AUTOMATICAMENTE pelo GitHub Actions --------- */
          export const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          };
          /* ---------------------------------------------------------------- */
          EOF

      # 3) Desliga o Jekyll para servir arquivos exatamente como estão
      - name: Disable Jekyll
        run: touch .nojekyll

      # Mostra o arquivo no log para depuração
      - run: cat js/firebaseConfig.js

      # 4) Publica a raiz no branch gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
